markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

#gauges_id: 503c5af6613f5d0f19000027
#google_analytics_id: UA-50755011-1
#google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

timezone: Asia/Beijing

future: true

collections:
  docs:
    output: true
    permalink: /:collection/:path/:year/:month/:day/:title/
  blog:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://christiein.github.io

twitter:
  username: ChristieInZhang

logo: img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
